// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1NKPCgypYLzAYX-ImpOCeVToRZz9xaF0',
    appId: '1:903835920800:web:85875b3e18879182679cc5',
    messagingSenderId: '903835920800',
    projectId: 'qrst-287813',
    authDomain: 'qrst-287813.firebaseapp.com',
    storageBucket: 'qrst-287813.appspot.com',
    measurementId: 'G-01DL3MBQQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH9XoedofXNfSMgtklIGxGfSaXt8RPJCM',
    appId: '1:903835920800:android:d73e23db2569e048679cc5',
    messagingSenderId: '903835920800',
    projectId: 'qrst-287813',
    storageBucket: 'qrst-287813.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1NKPCgypYLzAYX-ImpOCeVToRZz9xaF0',
    appId: '1:903835920800:web:10c110a54d017b7f679cc5',
    messagingSenderId: '903835920800',
    projectId: 'qrst-287813',
    authDomain: 'qrst-287813.firebaseapp.com',
    storageBucket: 'qrst-287813.appspot.com',
    measurementId: 'G-ZGZLF84WRL',
  );
}
